#ifndef __COMMON_MACRO_H__
#define __COMMON_MACRO_H__



#ifndef COMPLEX
#ifdef DOUBLE
//begin double
#define GEMM_SMALL_KERNEL_NN    DGEMM_SMALL_KERNEL_NN
#define GEMM_SMALL_KERNEL_NT    DGEMM_SMALL_KERNEL_NT
#define GEMM_SMALL_KERNEL_TN    DGEMM_SMALL_KERNEL_TN
#define GEMM_SMALL_KERNEL_TT    DGEMM_SMALL_KERNEL_TT

#define GEMM_SMALL_KERNEL_B0_NN    DGEMM_SMALL_KERNEL_B0_NN
#define GEMM_SMALL_KERNEL_B0_NT    DGEMM_SMALL_KERNEL_B0_NT
#define GEMM_SMALL_KERNEL_B0_TN    DGEMM_SMALL_KERNEL_B0_TN
#define GEMM_SMALL_KERNEL_B0_TT    DGEMM_SMALL_KERNEL_B0_TT

#define GEMM_NN     DGEMM_NN
#define GEMM_CN     DGEMM_TN
#define GEMM_TN     DGEMM_TN
#define GEMM_NC     DGEMM_NT
#define GEMM_NT     DGEMM_NT
#define GEMM_CC     DGEMM_TT
#define GEMM_CT     DGEMM_TT
#define GEMM_TC     DGEMM_TT
#define GEMM_TT     DGEMM_TT
#define GEMM_NR     DGEMM_NN
#define GEMM_TR     DGEMM_TN
#define GEMM_CR     DGEMM_TN
#define GEMM_RN     DGEMM_NN
#define GEMM_RT     DGEMM_NT
#define GEMM_RC     DGEMM_NT
#define GEMM_RR     DGEMM_NN
#define GEMM_ONCOPY   DGEMM_ONCOPY
#define GEMM_OTCOPY   DGEMM_OTCOPY
#define GEMM_INCOPY   DGEMM_INCOPY
#define GEMM_ITCOPY   DGEMM_ITCOPY

#define GEMM_BETA   DGEMM_BETA
#define GEMM_KERNEL_N   DGEMM_KERNEL
#define GEMM_KERNEL_L   DGEMM_KERNEL
#define GEMM_KERNEL_R   DGEMM_KERNEL
#define GEMM_KERNEL_B   DGEMM_KERNEL

#define	COPY_K			DCOPY_K
#define COPY_BLOCK  DCOPY_BLOCK

#define	NRM2_K			DNRM2_K
#define NRM2_BLOCK  DNRM2_BLOCK



#include "common_d.h"
//end double
#else
//begin sgemm
#define GEMM_SMALL_KERNEL_NN    SGEMM_SMALL_KERNEL_NN
#define GEMM_SMALL_KERNEL_NT    SGEMM_SMALL_KERNEL_NT
#define GEMM_SMALL_KERNEL_TN    SGEMM_SMALL_KERNEL_TN
#define GEMM_SMALL_KERNEL_TT    SGEMM_SMALL_KERNEL_TT

#define GEMM_SMALL_KERNEL_B0_NN    SGEMM_SMALL_KERNEL_B0_NN
#define GEMM_SMALL_KERNEL_B0_NT    SGEMM_SMALL_KERNEL_B0_NT
#define GEMM_SMALL_KERNEL_B0_TN    SGEMM_SMALL_KERNEL_B0_TN
#define GEMM_SMALL_KERNEL_B0_TT    SGEMM_SMALL_KERNEL_B0_TT

#define GEMM_NN     SGEMM_NN
#define GEMM_CN     SGEMM_TN
#define GEMM_TN     SGEMM_TN
#define GEMM_NC     SGEMM_NT
#define GEMM_NT     SGEMM_NT
#define GEMM_CC     SGEMM_TT
#define GEMM_CT     SGEMM_TT
#define GEMM_TC     SGEMM_TT
#define GEMM_TT     SGEMM_TT
#define GEMM_NR     SGEMM_NN
#define GEMM_TR     SGEMM_TN
#define GEMM_CR     SGEMM_TN
#define GEMM_RN     SGEMM_NN
#define GEMM_RT     SGEMM_NT
#define GEMM_RC     SGEMM_NT
#define GEMM_RR     SGEMM_NN

#define GEMM_ONCOPY   SGEMM_ONCOPY
#define GEMM_OTCOPY   SGEMM_OTCOPY
#define GEMM_INCOPY   SGEMM_INCOPY
#define GEMM_ITCOPY   SGEMM_ITCOPY

#define GEMM_BETA   SGEMM_BETA
#define GEMM_KERNEL_N   SGEMM_KERNEL
#define GEMM_KERNEL_L   SGEMM_KERNEL
#define GEMM_KERNEL_R   SGEMM_KERNEL
#define GEMM_KERNEL_B   SGEMM_KERNEL

#define COPY_K    SCOPY_K
#define COPY_BLOCK  SCOPY_BLOCK

#define	NRM2_K			SNRM2_K
#define NRM2_BLOCK  SNRM2_BLOCK


#include "common_s.h"
//end sgemm
#endif

#else
#ifdef DOUBLE
//begin zgemm
#define GEMM_SMALL_KERNEL_NN    ZGEMM_SMALL_KERNEL_NN
#define GEMM_SMALL_KERNEL_NT    ZGEMM_SMALL_KERNEL_NT
#define GEMM_SMALL_KERNEL_NR    ZGEMM_SMALL_KERNEL_NR
#define GEMM_SMALL_KERNEL_NC    ZGEMM_SMALL_KERNEL_NC

#define GEMM_SMALL_KERNEL_TN    ZGEMM_SMALL_KERNEL_TN
#define GEMM_SMALL_KERNEL_TT    ZGEMM_SMALL_KERNEL_TT
#define GEMM_SMALL_KERNEL_TR    ZGEMM_SMALL_KERNEL_TR
#define GEMM_SMALL_KERNEL_TC    ZGEMM_SMALL_KERNEL_TC

#define GEMM_SMALL_KERNEL_RN    ZGEMM_SMALL_KERNEL_RN
#define GEMM_SMALL_KERNEL_RT    ZGEMM_SMALL_KERNEL_RT
#define GEMM_SMALL_KERNEL_RR    ZGEMM_SMALL_KERNEL_RR
#define GEMM_SMALL_KERNEL_RC    ZGEMM_SMALL_KERNEL_RC

#define GEMM_SMALL_KERNEL_CN    ZGEMM_SMALL_KERNEL_CN
#define GEMM_SMALL_KERNEL_CT    ZGEMM_SMALL_KERNEL_CT
#define GEMM_SMALL_KERNEL_CR    ZGEMM_SMALL_KERNEL_CR
#define GEMM_SMALL_KERNEL_CC    ZGEMM_SMALL_KERNEL_CC

#define GEMM_SMALL_KERNEL_B0_NN    ZGEMM_SMALL_KERNEL_B0_NN
#define GEMM_SMALL_KERNEL_B0_NT    ZGEMM_SMALL_KERNEL_B0_NT
#define GEMM_SMALL_KERNEL_B0_NR    ZGEMM_SMALL_KERNEL_B0_NR
#define GEMM_SMALL_KERNEL_B0_NC    ZGEMM_SMALL_KERNEL_B0_NC

#define GEMM_SMALL_KERNEL_B0_TN    ZGEMM_SMALL_KERNEL_B0_TN
#define GEMM_SMALL_KERNEL_B0_TT    ZGEMM_SMALL_KERNEL_B0_TT
#define GEMM_SMALL_KERNEL_B0_TR    ZGEMM_SMALL_KERNEL_B0_TR
#define GEMM_SMALL_KERNEL_B0_TC    ZGEMM_SMALL_KERNEL_B0_TC

#define GEMM_SMALL_KERNEL_B0_RN    ZGEMM_SMALL_KERNEL_B0_RN
#define GEMM_SMALL_KERNEL_B0_RT    ZGEMM_SMALL_KERNEL_B0_RT
#define GEMM_SMALL_KERNEL_B0_RR    ZGEMM_SMALL_KERNEL_B0_RR
#define GEMM_SMALL_KERNEL_B0_RC    ZGEMM_SMALL_KERNEL_B0_RC

#define GEMM_SMALL_KERNEL_B0_CN    ZGEMM_SMALL_KERNEL_B0_CN
#define GEMM_SMALL_KERNEL_B0_CT    ZGEMM_SMALL_KERNEL_B0_CT
#define GEMM_SMALL_KERNEL_B0_CR    ZGEMM_SMALL_KERNEL_B0_CR
#define GEMM_SMALL_KERNEL_B0_CC    ZGEMM_SMALL_KERNEL_B0_CC

#define GEMM_NN     ZGEMM_NN
#define GEMM_CN     ZGEMM_CN
#define GEMM_TN     ZGEMM_TN
#define GEMM_NC     ZGEMM_NC
#define GEMM_NT     ZGEMM_NT
#define GEMM_CC     ZGEMM_CC
#define GEMM_CT     ZGEMM_CT
#define GEMM_TC     ZGEMM_TC
#define GEMM_TT     ZGEMM_TT
#define GEMM_NR     ZGEMM_NR
#define GEMM_TR     ZGEMM_TR
#define GEMM_CR     ZGEMM_CR
#define GEMM_RN     ZGEMM_RN
#define GEMM_RT     ZGEMM_RT
#define GEMM_RC     ZGEMM_RC
#define GEMM_RR     ZGEMM_RR

#define GEMM_ONCOPY   ZGEMM_ONCOPY
#define GEMM_OTCOPY   ZGEMM_OTCOPY
#define GEMM_INCOPY   ZGEMM_INCOPY
#define GEMM_ITCOPY   ZGEMM_ITCOPY

#define GEMM_BETA   ZGEMM_BETA
#define GEMM_KERNEL_N   ZGEMM_KERNEL_N
#define GEMM_KERNEL_L   ZGEMM_KERNEL_L
#define GEMM_KERNEL_R   ZGEMM_KERNEL_R
#define GEMM_KERNEL_B   ZGEMM_KERNEL_B

#define	COPY_K			ZCOPY_K
#define COPY_BLOCK  ZCOPY_BLOCK

#define	NRM2_K			ZNRM2_K
#define NRM2_BLOCK  ZNRM2_BLOCK

#include "common_z.h"
//end zgemm

#else
//begin cgemm
#define GEMM_SMALL_KERNEL_NN    CGEMM_SMALL_KERNEL_NN
#define GEMM_SMALL_KERNEL_NT    CGEMM_SMALL_KERNEL_NT
#define GEMM_SMALL_KERNEL_NR    CGEMM_SMALL_KERNEL_NR
#define GEMM_SMALL_KERNEL_NC    CGEMM_SMALL_KERNEL_NC

#define GEMM_SMALL_KERNEL_TN    CGEMM_SMALL_KERNEL_TN
#define GEMM_SMALL_KERNEL_TT    CGEMM_SMALL_KERNEL_TT
#define GEMM_SMALL_KERNEL_TR    CGEMM_SMALL_KERNEL_TR
#define GEMM_SMALL_KERNEL_TC    CGEMM_SMALL_KERNEL_TC

#define GEMM_SMALL_KERNEL_RN    CGEMM_SMALL_KERNEL_RN
#define GEMM_SMALL_KERNEL_RT    CGEMM_SMALL_KERNEL_RT
#define GEMM_SMALL_KERNEL_RR    CGEMM_SMALL_KERNEL_RR
#define GEMM_SMALL_KERNEL_RC    CGEMM_SMALL_KERNEL_RC

#define GEMM_SMALL_KERNEL_CN    CGEMM_SMALL_KERNEL_CN
#define GEMM_SMALL_KERNEL_CT    CGEMM_SMALL_KERNEL_CT
#define GEMM_SMALL_KERNEL_CR    CGEMM_SMALL_KERNEL_CR
#define GEMM_SMALL_KERNEL_CC    CGEMM_SMALL_KERNEL_CC

#define GEMM_SMALL_KERNEL_B0_NN    CGEMM_SMALL_KERNEL_B0_NN
#define GEMM_SMALL_KERNEL_B0_NT    CGEMM_SMALL_KERNEL_B0_NT
#define GEMM_SMALL_KERNEL_B0_NR    CGEMM_SMALL_KERNEL_B0_NR
#define GEMM_SMALL_KERNEL_B0_NC    CGEMM_SMALL_KERNEL_B0_NC

#define GEMM_SMALL_KERNEL_B0_TN    CGEMM_SMALL_KERNEL_B0_TN
#define GEMM_SMALL_KERNEL_B0_TT    CGEMM_SMALL_KERNEL_B0_TT
#define GEMM_SMALL_KERNEL_B0_TR    CGEMM_SMALL_KERNEL_B0_TR
#define GEMM_SMALL_KERNEL_B0_TC    CGEMM_SMALL_KERNEL_B0_TC

#define GEMM_SMALL_KERNEL_B0_RN    CGEMM_SMALL_KERNEL_B0_RN
#define GEMM_SMALL_KERNEL_B0_RT    CGEMM_SMALL_KERNEL_B0_RT
#define GEMM_SMALL_KERNEL_B0_RR    CGEMM_SMALL_KERNEL_B0_RR
#define GEMM_SMALL_KERNEL_B0_RC    CGEMM_SMALL_KERNEL_B0_RC

#define GEMM_SMALL_KERNEL_B0_CN    CGEMM_SMALL_KERNEL_B0_CN
#define GEMM_SMALL_KERNEL_B0_CT    CGEMM_SMALL_KERNEL_B0_CT
#define GEMM_SMALL_KERNEL_B0_CR    CGEMM_SMALL_KERNEL_B0_CR
#define GEMM_SMALL_KERNEL_B0_CC    CGEMM_SMALL_KERNEL_B0_CC

#define GEMM_NN     CGEMM_NN
#define GEMM_CN     CGEMM_CN
#define GEMM_TN     CGEMM_TN
#define GEMM_NC     CGEMM_NC
#define GEMM_NT     CGEMM_NT
#define GEMM_CC     CGEMM_CC
#define GEMM_CT     CGEMM_CT
#define GEMM_TC     CGEMM_TC
#define GEMM_TT     CGEMM_TT
#define GEMM_NR     CGEMM_NR
#define GEMM_TR     CGEMM_TR
#define GEMM_CR     CGEMM_CR
#define GEMM_RN     CGEMM_RN
#define GEMM_RT     CGEMM_RT
#define GEMM_RC     CGEMM_RC
#define GEMM_RR     CGEMM_RR

#define GEMM_ONCOPY   CGEMM_ONCOPY
#define GEMM_OTCOPY   CGEMM_OTCOPY
#define GEMM_INCOPY   CGEMM_INCOPY
#define GEMM_ITCOPY   CGEMM_ITCOPY

#define GEMM_BETA   CGEMM_BETA
#define GEMM_KERNEL_N   CGEMM_KERNEL_N
#define GEMM_KERNEL_L   CGEMM_KERNEL_L
#define GEMM_KERNEL_R   CGEMM_KERNEL_R
#define GEMM_KERNEL_B   CGEMM_KERNEL_B

#define	COPY_K			CCOPY_K
#define COPY_BLOCK  CCOPY_BLOCK

#define	NRM2_K			CNRM2_K
#define NRM2_BLOCK  CNRM2_BLOCK

#include "common_c.h"
//end cgemm
#endif
#endif//end COMPLEX





#endif
