#ifndef __COMMON_PARAM_H__
#define __COMMON_PARAM_H__

#define GEMM_OFFSET_A GEMM_DEFAULT_OFFSET_A
#define GEMM_OFFSET_B GEMM_DEFAULT_OFFSET_B
#define GEMM_ALIGN  GEMM_DEFAULT_ALIGN


#define	SGEMM_P		SGEMM_DEFAULT_P
#define	SGEMM_Q		SGEMM_DEFAULT_Q
#define	SGEMM_R		SGEMM_DEFAULT_R
#define SGEMM_UNROLL_M	SGEMM_DEFAULT_UNROLL_M
#define SGEMM_UNROLL_N	SGEMM_DEFAULT_UNROLL_N
#ifdef  SGEMM_DEFAULT_UNROLL_MN
#define SGEMM_UNROLL_MN	SGEMM_DEFAULT_UNROLL_MN
#else
#define SGEMM_UNROLL_MN	MAX((SGEMM_UNROLL_M), (SGEMM_UNROLL_N))
#endif

#define	DGEMM_P		DGEMM_DEFAULT_P
#define	DGEMM_Q		DGEMM_DEFAULT_Q
#define	DGEMM_R		DGEMM_DEFAULT_R
#define DGEMM_UNROLL_M	DGEMM_DEFAULT_UNROLL_M
#define DGEMM_UNROLL_N	DGEMM_DEFAULT_UNROLL_N
#ifdef  DGEMM_DEFAULT_UNROLL_MN
#define DGEMM_UNROLL_MN	DGEMM_DEFAULT_UNROLL_MN
#else
#define DGEMM_UNROLL_MN	MAX((DGEMM_UNROLL_M), (DGEMM_UNROLL_N))
#endif

#define	CGEMM_P		CGEMM_DEFAULT_P
#define	CGEMM_Q		CGEMM_DEFAULT_Q
#define	CGEMM_R		CGEMM_DEFAULT_R
#define CGEMM_UNROLL_M	CGEMM_DEFAULT_UNROLL_M
#define CGEMM_UNROLL_N	CGEMM_DEFAULT_UNROLL_N
#ifdef  CGEMM_DEFAULT_UNROLL_MN
#define CGEMM_UNROLL_MN	CGEMM_DEFAULT_UNROLL_MN
#else
#define CGEMM_UNROLL_MN	MAX((CGEMM_UNROLL_M), (CGEMM_UNROLL_N))
#endif

#define	ZGEMM_P		ZGEMM_DEFAULT_P
#define	ZGEMM_Q		ZGEMM_DEFAULT_Q
#define	ZGEMM_R		ZGEMM_DEFAULT_R
#define ZGEMM_UNROLL_M	ZGEMM_DEFAULT_UNROLL_M
#define ZGEMM_UNROLL_N	ZGEMM_DEFAULT_UNROLL_N
#ifdef  ZGEMM_DEFAULT_UNROLL_MN
#define ZGEMM_UNROLL_MN	ZGEMM_DEFAULT_UNROLL_MN
#else
#define ZGEMM_UNROLL_MN	MAX((ZGEMM_UNROLL_M), (ZGEMM_UNROLL_N))
#endif



#ifndef COMPLEX
#if defined(DOUBLE)
#define GEMM_P			DGEMM_P
#define GEMM_Q			DGEMM_Q
#define GEMM_R			DGEMM_R
#define GEMM_UNROLL_M		DGEMM_UNROLL_M
#define GEMM_UNROLL_N		DGEMM_UNROLL_N
#define GEMM_UNROLL_MN		DGEMM_UNROLL_MN
#define GEMM_DEFAULT_P		DGEMM_DEFAULT_P
#define GEMM_DEFAULT_Q		DGEMM_DEFAULT_Q
#define GEMM_DEFAULT_R		DGEMM_DEFAULT_R
#define GEMM_DEFAULT_UNROLL_M	DGEMM_DEFAULT_UNROLL_M
#define GEMM_DEFAULT_UNROLL_N	DGEMM_DEFAULT_UNROLL_N
#else
#define GEMM_P			SGEMM_P
#define GEMM_Q			SGEMM_Q
#define GEMM_R			SGEMM_R
#define GEMM_UNROLL_M		SGEMM_UNROLL_M
#define GEMM_UNROLL_N		SGEMM_UNROLL_N
#define GEMM_UNROLL_MN		SGEMM_UNROLL_MN
#define GEMM_DEFAULT_P		SGEMM_DEFAULT_P
#define GEMM_DEFAULT_Q		SGEMM_DEFAULT_Q
#define GEMM_DEFAULT_R		SGEMM_DEFAULT_R
#define GEMM_DEFAULT_UNROLL_M	SGEMM_DEFAULT_UNROLL_M
#define GEMM_DEFAULT_UNROLL_N	SGEMM_DEFAULT_UNROLL_N
#endif
#else
#if defined(DOUBLE)
#define GEMM_P			ZGEMM_P
#define GEMM_Q			ZGEMM_Q
#define GEMM_R			ZGEMM_R
#define GEMM_UNROLL_M		ZGEMM_UNROLL_M
#define GEMM_UNROLL_N		ZGEMM_UNROLL_N
#define GEMM_UNROLL_MN		ZGEMM_UNROLL_MN
#define GEMM_DEFAULT_P		ZGEMM_DEFAULT_P
#define GEMM_DEFAULT_Q		ZGEMM_DEFAULT_Q
#define GEMM_DEFAULT_R		ZGEMM_DEFAULT_R
#define GEMM_DEFAULT_UNROLL_M	ZGEMM_DEFAULT_UNROLL_M
#define GEMM_DEFAULT_UNROLL_N	ZGEMM_DEFAULT_UNROLL_N
#else
#define GEMM_P			CGEMM_P
#define GEMM_Q			CGEMM_Q
#define GEMM_R			CGEMM_R
#define GEMM_UNROLL_M		CGEMM_UNROLL_M
#define GEMM_UNROLL_N		CGEMM_UNROLL_N
#define GEMM_UNROLL_MN		CGEMM_UNROLL_MN
#define GEMM_DEFAULT_P		CGEMM_DEFAULT_P
#define GEMM_DEFAULT_Q		CGEMM_DEFAULT_Q
#define GEMM_DEFAULT_R		CGEMM_DEFAULT_R
#define GEMM_DEFAULT_UNROLL_M	CGEMM_DEFAULT_UNROLL_M
#define GEMM_DEFAULT_UNROLL_N	CGEMM_DEFAULT_UNROLL_N
#endif
#endif

#ifndef SGEMM_DEFAULT_R
#define SGEMM_DEFAULT_R (((BUFFER_SIZE - ((SGEMM_DEFAULT_P * SGEMM_DEFAULT_Q *  4 + GEMM_DEFAULT_OFFSET_A + GEMM_DEFAULT_ALIGN) & ~GEMM_DEFAULT_ALIGN)) / (SGEMM_DEFAULT_Q *  4) - 15) & ~15UL)
#endif

#ifndef DGEMM_DEFAULT_R
#define DGEMM_DEFAULT_R (((BUFFER_SIZE - ((DGEMM_DEFAULT_P * DGEMM_DEFAULT_Q *  8 + GEMM_DEFAULT_OFFSET_A + GEMM_DEFAULT_ALIGN) & ~GEMM_DEFAULT_ALIGN)) / (DGEMM_DEFAULT_Q *  8) - 15) & ~15UL)
#endif

#ifndef CGEMM_DEFAULT_R
#define CGEMM_DEFAULT_R (((BUFFER_SIZE - ((CGEMM_DEFAULT_P * CGEMM_DEFAULT_Q *  8 + GEMM_DEFAULT_OFFSET_A + GEMM_DEFAULT_ALIGN) & ~GEMM_DEFAULT_ALIGN)) / (CGEMM_DEFAULT_Q *  8) - 15) & ~15UL)
#endif

#ifndef ZGEMM_DEFAULT_R
#define ZGEMM_DEFAULT_R (((BUFFER_SIZE - ((ZGEMM_DEFAULT_P * ZGEMM_DEFAULT_Q * 16 + GEMM_DEFAULT_OFFSET_A + GEMM_DEFAULT_ALIGN) & ~GEMM_DEFAULT_ALIGN)) / (ZGEMM_DEFAULT_Q * 16) - 15) & ~15UL)
#endif





#endif
