#ifndef __PARAM_H__
#define __PARAM_H__

#define GEMM_DEFAULT_OFFSET_A  64
#define GEMM_DEFAULT_OFFSET_B 256
#define GEMM_DEFAULT_ALIGN (BLASLONG)0x01ffffUL


#define SGEMM_DEFAULT_UNROLL_M  16
#define SGEMM_DEFAULT_UNROLL_N  4

#define DGEMM_DEFAULT_UNROLL_M  8
#define DGEMM_DEFAULT_UNROLL_N  4

#define CGEMM_DEFAULT_UNROLL_M  8
#define CGEMM_DEFAULT_UNROLL_N  4

#define ZGEMM_DEFAULT_UNROLL_M  4
#define ZGEMM_DEFAULT_UNROLL_N  4


//#define SGEMM_DEFAULT_P 512
//#define DGEMM_DEFAULT_P 256
//#define CGEMM_DEFAULT_P 256
//#define ZGEMM_DEFAULT_P 128
//
//#define SGEMM_DEFAULT_Q 1024
//#define DGEMM_DEFAULT_Q 512
//#define CGEMM_DEFAULT_Q 512
//#define ZGEMM_DEFAULT_Q 512
//
//#define SGEMM_DEFAULT_R 4096
//#define DGEMM_DEFAULT_R 4096
//#define CGEMM_DEFAULT_R 4096
//#define ZGEMM_DEFAULT_R 2048

#define SGEMM_DEFAULT_P 16 
#define DGEMM_DEFAULT_P 4096
#define CGEMM_DEFAULT_P 16 
#define ZGEMM_DEFAULT_P 16 

#define SGEMM_DEFAULT_Q 16 
#define DGEMM_DEFAULT_Q 4096
#define CGEMM_DEFAULT_Q 16 
#define ZGEMM_DEFAULT_Q 16 

#define SGEMM_DEFAULT_R 16 
#define DGEMM_DEFAULT_R 16
#define CGEMM_DEFAULT_R 16 
#define ZGEMM_DEFAULT_R 16 

#define SCOPY_BLOCK 4000
#define DCOPY_BLOCK 2000
#define CCOPY_BLOCK 2000
#define ZCOPY_BLOCK 1000

#define SNRM2_BLOCK 4000
#define DNRM2_BLOCK 2000
#define CNRM2_BLOCK 2000
#define ZNRM2_BLOCK 1000

//#define SGEMM_DEFAULT_P 16 
//#define DGEMM_DEFAULT_P 8
//#define CGEMM_DEFAULT_P 16 
//#define ZGEMM_DEFAULT_P 16 
//
//#define SGEMM_DEFAULT_Q 4 
//#define DGEMM_DEFAULT_Q 1
//#define CGEMM_DEFAULT_Q 16 
//#define ZGEMM_DEFAULT_Q 16 
//
//#define SGEMM_DEFAULT_R 4 
//#define DGEMM_DEFAULT_R 4
//#define CGEMM_DEFAULT_R 16 
//#define ZGEMM_DEFAULT_R 16 

#endif
